Tpb06
leandrosax10/saudeDaRua pull request #21
Opened 2022-01-22 00:00 UTC by Maridh

Adjusting path for Header.

2022-01-22 03:10 UTC, priscilaandreani requested changes

2022-01-22 03:10 UTC, priscilaandreani commented on src/pages/Home/Home.jsx
> +      <Header />
o Header deve ocupar sempre 100% da tela, portanto, deve ser importado fora de Structure. Lá no App, por enquanto e depois dentor das rotas.

2022-01-22 03:10 UTC, priscilaandreani commented on src/shared/components/Header/components/Header.jsx
> +    <div>
por que utilizar div dentro de div?

2022-01-22 03:10 UTC, priscilaandreani commented on src/shared/components/Header/components/Header.jsx
> +      <div className="header">
para utilizar o estilo que vc criou com styled-component, deveria utilizar a tag

```
<Header> 
   <img src={logo} alt="Logo Saúde da Rua" className="logo" />
</Header>
```

2022-01-22 03:10 UTC, priscilaandreani commented on src/shared/components/Header/components/Header.style.js
> +import styled from 'styled-components';
não tem estilo nenhum pro Header?

2022-01-22 16:06 UTC, merged

2022-01-25 23:32 UTC, Maridh commented on src/pages/Home/Home.jsx
> +      <Header />
Feito, vou subir

2022-01-25 23:32 UTC, Maridh commented on src/shared/components/Header/components/Header.jsx
> +    <div>
Entendi, realemte desnecessário. Feito.