Fix tpb08 r
leandrosax10/saudeDaRua pull request #28
Opened 2022-01-28 11:43 UTC by leandrosax10

@priscilaandreani

2022-01-28 13:12 UTC, priscilaandreani requested changes

2022-01-28 13:12 UTC, priscilaandreani commented on src/assets/index.js
> +import MapImagStyle from './mapa.png';
Você pode utilizar a importação via index, para organizar melhor.

2022-01-28 13:12 UTC, priscilaandreani commented on src/pages/Home/Home.jsx
> +      <Header />
O Header não é mais importado aqui. Ele fica na estrutura.

2022-01-28 13:12 UTC, priscilaandreani commented on src/pages/Home/components/WhereAreWe/components/WrapperTextWhere/WrapperTextWhere.jsx
> +      <WhereAreWeSubTitle2>Saúde da Rua - SP</WhereAreWeSubTitle2>
Comentário que fiz na quarta passada:
- Cada uma das sedes vai ser um objeto para interagir, portanto não devem ser utilizados dessa forma. 
- Transformar cada um em um compoenete para utilizar a referencia.
- Faltou a animação com o hover aqui.

2022-01-28 13:12 UTC, priscilaandreani commented on src/pages/Home/components/WhereAreWe/components/WrapperTextWhere/WrapperTextWhere.style.js
> +  color: ${(props) => props.theme.colors.primary_light};
a cor da tipografia de p está (ou deveria estar) setada em global, então não precisa ser determinada aqui.

2022-01-28 13:12 UTC, priscilaandreani commented on src/pages/Home/components/WhereAreWe/components/WrapperTextWhere/WrapperTextWhere.style.js
> +  color: ${(props) => props.theme.colors.primary_light};
a cor da tipografia de h2 está (ou deveria estar) setada em global, então não precisa ser determinada aqui.

2022-01-28 13:12 UTC, priscilaandreani commented on src/pages/Home/components/WhereAreWe/components/WrapperTextWhere/WrapperTextWhere.style.js
> +  color: ${(props) => props.theme.colors.primary};
P é utilizado para texto corrido, se é um subtitulo o ideal seria procurar um h que encaixasse segundo o guia de estilo.

2022-01-28 13:26 UTC, leandrosax10 commented on src/assets/index.js
> +import MapImagStyle from './mapa.png';
Foi importado no Index

2022-01-28 13:32 UTC, leandrosax10 commented on src/pages/Home/Home.jsx
> +      <Header />
Ok, vou retirar.

2022-01-28 14:57 UTC, leandrosax10 commented on src/pages/Home/components/WhereAreWe/components/WrapperTextWhere/WrapperTextWhere.style.js
> +  color: ${(props) => props.theme.colors.primary_light};
Setado!

2022-01-28 14:57 UTC, leandrosax10 commented on src/pages/Home/components/WhereAreWe/components/WrapperTextWhere/WrapperTextWhere.style.js
> +  color: ${(props) => props.theme.colors.primary_light};
Setado!

2022-01-28 15:12 UTC, leandrosax10 commented on src/pages/Home/components/WhereAreWe/components/WrapperTextWhere/WrapperTextWhere.style.js
> +  color: ${(props) => props.theme.colors.primary};
Feito!

2022-02-07 21:38 UTC, priscilaandreani requested changes
- Tem uma bolinha que está pra fora do mapa
- o alinhamento da página está fora do centro

2022-02-07 21:38 UTC, priscilaandreani commented on src/pages/Home/components/WhereAreWe/components/WrapperTextWhere/WrapperTextWhere.jsx
> +      <Circle>
as funções aqui não deveriam ser as mesmas do componente principal? assim o clique nos dois lugares funcionam da mesma forma

2022-02-07 21:38 UTC, priscilaandreani commented on src/pages/Home/components/WhereAreWe/components/WrapperTextWhere/WrapperTextWhere.style.js
> +  /*
se ta comentado e não vai usar, pode excluir

2022-02-07 21:38 UTC, priscilaandreani commented on src/pages/Home/components/WhereAreWe/components/WrapperTextWhere/WrapperTextWhere.style.js
> +export const CircleSaoCarlos = styled.p`
pq esse circle é um P e os outros uma div?

2022-02-07 22:11 UTC, leandrosax10 commented on src/pages/Home/components/WhereAreWe/components/WrapperTextWhere/WrapperTextWhere.style.js
> +  /*
ok!

2022-02-07 22:11 UTC, leandrosax10 commented on src/pages/Home/components/WhereAreWe/components/WrapperTextWhere/WrapperTextWhere.style.js
> +export const CircleSaoCarlos = styled.p`
Acertado!

2022-02-07 23:27 UTC, leandrosax10 commented on src/pages/Home/components/WhereAreWe/components/WrapperTextWhere/WrapperTextWhere.jsx
> +      <Circle>
Tentei assim e eu não deu certo.

2022-02-15 12:42 UTC, merged