Tpb14
leandrosax10/saudeDaRua pull request #29
Opened 2022-01-29 00:42 UTC by Maridh

Finished carousel structure. Next step styling.

2022-01-31 15:14 UTC, priscilaandreani requested changes
A branch está finalizada?

2022-01-31 15:14 UTC, priscilaandreani commented on src/pages/Home/components/OurActions/components/Carousel.js
> +          Next
?

2022-01-31 15:28 UTC, Maridh commented
Em andamento previsão pra hoje.

Em seg., 31 de jan. de 2022 às 12:15, Priscila Andreani <
***@***.***> escreveu:

> ***@***.**** requested changes on this pull request.
>
> A branch está finalizada?
> ------------------------------
>
> In src/pages/Home/components/OurActions/components/Carousel.js
> <https://github.com/leandrosax10/saudeDaRua/pull/29#discussion_r795766823>
> :
>
> > +              className={`${index === activeIndex ? 'active' : ''} `}
>
> +              onClick={() => {
>
> +                updateIndex(index);
>
> +              }}
>
> +            >
>
> +              {index + 1}
>
> +            </button>
>
> +          );
>
> +        })}
>
> +
>
> +        <button
>
> +          onClick={() => {
>
> +            updateIndex(activeIndex + 1);
>
> +          }}
>
> +        >
>
> +          Next
>
>
> ?
> ------------------------------
>
> In src/pages/Home/components/OurActions/components/SliderData.jsx
> <https://github.com/leandrosax10/saudeDaRua/pull/29#discussion_r795767081>
> :
>
> > @@ -0,0 +1,14 @@
>
> +import Carousel, { CarouselItem } from './Carousel';
>
> +import { Container } from './Carousel.style';
>
> +
>
> +const SliderData = () => (
>
> +  <Container>
>
> +    <Carousel>
>
> +      <CarouselItem>Teste</CarouselItem>
>
>
> ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/leandrosax10/saudeDaRua/pull/29#pullrequestreview-867989346>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANGWVSXQJVK6MQCADIPVQHTUY2RQBANCNFSM5NCESADQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-07 22:07 UTC, priscilaandreani requested changes
- Ajustar os frames que estão fora do lugar
- Remover palavras em ingles do layout
- Pra que servem essas elipses? Se apenas dermarcam espaços, podem ser feitas com uma div e não precisam ser uma img 
-

2022-02-07 22:07 UTC, priscilaandreani commented on package.json
>      "@testing-library/react": "^12.1.2",
Se não está utilizando a lib, ela deve ser removida daqui ;)

2022-03-26 13:57 UTC, priscilaandreani approved these changes

2022-03-26 14:05 UTC, priscilaandreani approved these changes

2022-03-26 14:05 UTC, priscilaandreani commented on src/pages/Home/components/OurActions/SliderData.jsx
> +      <CarouselItem>
Esse componente poderia ser reutilizável e receber as infos através de props pra um código mais limpo

2022-03-26 14:05 UTC, priscilaandreani commented on src/pages/Home/components/OurActions/components/Carousel.js
> +    }, 1000);
Esse tempo é suficiente para a leitura do texto todo?

2022-03-26 14:05 UTC, priscilaandreani commented on src/pages/Home/components/OurActions/components/Carousel.style.js
> +export const FrameImg1 = styled.div`
Existe um componente reutilizável para os frames

2022-04-06 22:41 UTC, merged