Final adjustments to the image and opacity
leandrosax10/saudeDaRua pull request #36
Opened 2022-02-18 20:10 UTC by Maridh

2022-02-18 21:31 UTC, priscilaandreani requested changes

2022-02-18 21:31 UTC, priscilaandreani commented on src/pages/Home/components/Banner/components/Banner.jsx
> +import img from '../../../../../assets/voluntary.jpg';
importação deve ser sempre feita pelo index

2022-02-18 21:31 UTC, priscilaandreani commented on src/pages/Home/components/Banner/components/Banner.jsx
>        <Text>
não devemos colocar uma img dentro de um h1

2022-02-18 21:31 UTC, priscilaandreani commented on src/pages/Home/components/Banner/components/Banner.jsx
>          <h1>
tem dois h1 na página, o correto é existir apenas 1 por layout

2022-02-18 21:31 UTC, priscilaandreani commented on src/pages/Home/components/Banner/components/Banner.jsx
> +        <img className="bannerPhoto" src={img} alt="Foto dos volutários" />
a imagem ainda está distorcida em telas maiores, falar com ux de limitar o tamanho para 1170px

2022-02-18 21:31 UTC, priscilaandreani commented on src/pages/Home/components/Banner/components/Banner.jsx
>      <div className="banner">
essa div banner é desnecessária, já que o componente BannerContainer faz o mesmo papel dela

2022-02-20 12:55 UTC, Maridh commented on src/pages/Home/components/Banner/components/Banner.jsx
> +import img from '../../../../../assets/voluntary.jpg';
Tentei mudar mas deu erro, fala que não localiza a foto no index, uma questão de exportação.

2022-02-22 20:25 UTC, priscilaandreani commented on src/pages/Home/components/Banner/components/Banner.jsx
> +import img from '../../../../../assets/voluntary.jpg';
adicionar o mapa no index.js da pasta de assets

importar e exportar seguindo o padrão (ver o código)
e então, importar aqui via index:

import {mapa} from '../../../../../../assets';

dessa forma, você garante que caso o src da imagem mude, sua aplicação não quebra ;)

2022-02-22 20:27 UTC, priscilaandreani commented on src/pages/Home/components/Banner/components/Banner.jsx
> +import img from '../../../../../assets/voluntary.jpg';
Questão de exportação: vc precisa verificar porque seu arquivo está exportado errado e importar da forma certa

2022-02-22 20:55 UTC, Maridh commented
Tentando resolver pq quebra

Em ter, 22 de fev de 2022 17:27, Priscila Andreani ***@***.***>
escreveu:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/pages/Home/components/Banner/components/Banner.jsx
> <https://github.com/leandrosax10/saudeDaRua/pull/36#discussion_r812329612>
> :
>
> > @@ -1,11 +1,13 @@
>
>  import React from 'react';
>
>  import { BannerContainer, Text, Button } from './Banner.style';
>
>  import { ButtonDonation } from '../../../../../shared/components/index';
>
> +import img from '../../../../../assets/voluntary.jpg';
>
>
> Questão de exportação: vc precisa verificar porque seu arquivo está
> exportado errado e importar da forma certa
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/leandrosax10/saudeDaRua/pull/36#discussion_r812329612>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANGWVSRRDO43IAYFPJWPT2TU4PWSBANCNFSM5OY6UO3A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-22 21:16 UTC, Maridh commented on src/pages/Home/components/Banner/components/Banner.jsx
> +import img from '../../../../../assets/voluntary.jpg';
Consegui, eram as chaves

2022-02-22 21:23 UTC, Maridh commented on src/pages/Home/components/Banner/components/Banner.jsx
> +        <img className="bannerPhoto" src={img} alt="Foto dos volutários" />
width: 100%;
 max-width: 90rem;

Pesquisei e achei essa solução, resolve assim?

2022-02-22 21:27 UTC, Maridh commented on src/pages/Home/components/Banner/components/Banner.jsx
>          <h1>
Transformei em div, aparentemente resolveu.

2022-02-22 21:28 UTC, Maridh commented on src/pages/Home/components/Banner/components/Banner.jsx
>        <Text>
Aparentemente resolvido

2022-02-23 02:12 UTC, priscilaandreani commented on src/pages/Home/components/Banner/components/Banner.jsx
> +        <img className="bannerPhoto" src={img} alt="Foto dos volutários" />
Sim, mas ainda não está centralizado :(

2022-02-23 02:15 UTC, priscilaandreani requested changes

2022-02-23 02:15 UTC, priscilaandreani commented on src/pages/Home/components/Banner/components/Banner.jsx
> +    <Button>
Esse botão em algum momento vai precisar ser refatorado para virar um componente genérico, já anota ai junto com os seus todo's ;)

2022-02-23 02:15 UTC, priscilaandreani commented on src/pages/Home/components/WhereAreWe/WhereAreWe.jsx
>  import { WrapperTextWhere } from './components';
Precisa fazer o rebase da sua branch para pegar a versão atualizada desse componente

2022-05-04 22:15 UTC, closed without merging