Acerto do componente
leandrosax10/saudeDaRua pull request #37
Opened 2022-02-19 14:00 UTC by leandrosax10

@priscilaandreani  Consertei!

2022-02-19 23:29 UTC, priscilaandreani commented
boaa! 

única coisa, segue o padrão no nome do estilos:
- componente: PhotoMap.jsx
- estilo: PhotoMap.styles.jsx e não MapStyles.js

2022-02-21 14:38 UTC, leandrosax10 commented
> boaa!
> 
> coisa única, segue o padrão no nome do estilos:
> 
> * componente: PhotoMap.jsx
> * estilo: PhotoMap.style.jsx e não MapStyles.js
> 
> assim quando pesquisamos por um componente, fica mais fácil de achar o seu correspondente de estilo por ex.: control + p "nomeDoComponente"

No componente de estilo ponho a extensão jsx mesmo?? (PhotoMap.style.jsx )

2022-02-22 13:54 UTC, priscilaandreani commented
> > boaa!
> > coisa única, segue o padrão no nome do estilos:
> > 
> > * componente: PhotoMap.jsx
> > * estilo: PhotoMap.style.jsx e não MapStyles.js
> > 
> > assim quando pesquisamos por um componente, fica mais fácil de achar o seu correspondente de estilo por ex.: control + p "nomeDoComponente"
> 
> No componente de estilo ponho a extensão jsx mesmo?? (PhotoMap.style.jsx )

Não. o jsx é utilizado apenas quando o React está importado dentro do componente. E neste momento não há import no componente.

2022-02-22 13:56 UTC, leandrosax10 commented
> > > boaa!
> > > coisa única, segue o padrão no nome do estilos:
> > > 
> > > * componente: PhotoMap.jsx
> > > * estilo: PhotoMap.style.jsx e não MapStyles.js
> > > 
> > > assim quando pesquisamos por um componente, fica mais fácil de achar o seu correspondente de estilo por ex.: control + p "nomeDoComponente"
> > 
> > 
> > No componente de estilo ponho a extensão jsx mesmo?? (PhotoMap.style.jsx )
> 
> Não. o jsx é utilizado apenas quando o React está importado dentro do componente. E neste momento não há import no componente.

Ah sim!! tá ótimo

2022-02-22 14:08 UTC, priscilaandreani requested changes

2022-02-22 14:08 UTC, priscilaandreani commented on src/pages/Home/components/WhereAreWe/components/MapPhoto/PhotoMap.jsx
>  import mapa from '../../../../../../assets/mapa.png';
importar via index

2022-02-22 14:08 UTC, priscilaandreani commented on src/pages/Home/components/WhereAreWe/components/MapPhoto/PhotoMap.jsx
> +import { MapImagStyle } from './PhotoMap.Styles';
'style' deve ser em letra minúscula

2022-02-22 14:25 UTC, priscilaandreani requested changes

2022-02-22 14:25 UTC, priscilaandreani commented on src/pages/Home/components/WhereAreWe/components/MapPhoto/PhotoMap.jsx
>  import mapa from '../../../../../../assets/mapa.png';
- adicionar o mapa no index.js da pasta de assets 
- importar e exportar seguindo o padrão (ver o código)
e então, importar aqui via index:

- import {mapa} from '../../../../../../assets';

dessa forma, você garante que caso o src da imagem mude, sua aplicação não quebra ;)

2022-02-22 14:29 UTC, priscilaandreani requested changes

2022-02-22 14:29 UTC, priscilaandreani commented on src/pages/Home/components/WhereAreWe/components/MapPhoto/PhotoMap.Styles.js
a pasta e o componente devem ter o mesmo nome!

Pasta: PhotoMap
Componente: PhotoMap.jsx
Estilo: PhotoMap.style.js

2022-02-22 20:28 UTC, priscilaandreani approved these changes
Boaaa! :D

2022-02-22 20:35 UTC, merged