Review ux
leandrosax10/saudeDaRua pull request #53
Opened 2022-04-08 01:18 UTC by Maridh

Adjust layout suggested by UX team.

2022-04-11 12:57 UTC, lucas-lm commented
We are still missing some adjustments, but most of them were already applied

2022-04-11 14:31 UTC, priscilaandreani requested changes
dentro do WrapperTextWhere precisa ser feita a seguinte modificação:
`const [sede, setSede] = useState(true);`

2022-04-11 14:31 UTC, priscilaandreani commented on src/pages/Home/components/OurActions/SliderData.style.js
> +      color: ${(props) => props.theme.colors.light};
A cor aqui está errada, deveria ser #B2DFFC.
Os espaçamentos também não parecem corretos, uma vez que deveria ter uma margem superior maior.
A tipografia deveria ser bold.

2022-04-11 14:31 UTC, priscilaandreani commented on src/pages/Home/components/OurActions/SliderData.style.js
> +      font-weight: 700px;
* font-weight: 700;

2022-04-11 14:31 UTC, priscilaandreani commented on src/pages/Home/components/OurActions/SliderData.jsx
>              Veja nossas <span>ações</span>
A cor de "ações" continua errada

2022-04-11 14:31 UTC, priscilaandreani commented on src/pages/Donation/components/HelpNow/HelpNow.jsx
>            >
linha 59:
texto foi alterado para "Para doar com..."

2022-04-11 14:31 UTC, priscilaandreani commented on src/shared/components/Quotation/Quotation.style.js
>  export const Author = styled.p`
adicionar fonte itálica para o autor

2022-04-11 14:40 UTC, priscilaandreani commented on src/pages/Home/components/Banner/Banner.style.js
> +  margin: 0 auto 116px auto;
dica: dá pra abreviar para 
`margin: 0 auto 116px; `

2022-04-13 02:37 UTC, lucas-lm commented on src/pages/Donation/components/HelpNow/HelpNow.jsx
>            </HelpOptionsContainer>
Resolvido.

2022-04-13 02:38 UTC, lucas-lm commented on src/pages/Donation/components/HelpNow/HelpNow.jsx
>            >
Resolvido.

2022-04-13 02:38 UTC, lucas-lm commented on src/pages/Donation/components/HelpNow/HelpNow.jsx
>          {values.map((v) => (
Resolvido.

2022-04-13 03:34 UTC, priscilaandreani commented on src/pages/Home/components/OurActions/SliderData.jsx
>  import { Container } from './components/Carousel.style';
O correto seria não utilizar esse Container do Carousel aqui, uma vez que ele deveria estar estilizando o arquivo Carousel.jsx e não o SliderData. Tem um problema de arquitetura aqui.

2022-04-13 03:34 UTC, priscilaandreani commented on src/pages/Home/components/OurActions/SliderData.style.js
> +      font-weight: 700px;
A propriedade font-weight está repetida aqui

2022-04-13 23:53 UTC, merged