TPB30 - Input date
leandrosax10/saudeDaRua pull request #60
Opened 2022-04-29 22:14 UTC by leandrosax10

@priscilaandreani

2022-04-29 22:55 UTC, priscilaandreani requested changes

2022-04-29 22:55 UTC, priscilaandreani commented on src/shared/components/InputDate/InputDate.jsx
> +const InputDate = () => {
para ser reutilizável, precisa receber as propriedades que podem ser alteradas

2022-04-29 22:55 UTC, priscilaandreani commented on src/shared/components/InputDate/InputDate.jsx
> +    <label>
a label é o título do campo, não tem porque ele englobar o input

2022-04-29 22:55 UTC, priscilaandreani commented on src/shared/components/InputDate/InputDate.jsx
> +        {...register('dataNascimento')}
quando vc seta o register fixo, o componente deixa de ser reutilizável

2022-04-30 00:07 UTC, leandrosax10 commented on src/shared/components/InputDate/InputDate.jsx
> +const InputDate = () => {
Essa parte das propriedades não entendi, quais seriam?

2022-04-30 00:07 UTC, leandrosax10 commented on src/shared/components/InputDate/InputDate.jsx
> +    <label>
ok, refeito

2022-04-30 00:07 UTC, leandrosax10 commented on src/shared/components/InputDate/InputDate.jsx
> +        {...register('dataNascimento')}
Retirei.

2022-04-30 00:33 UTC, priscilaandreani requested changes

2022-04-30 00:33 UTC, priscilaandreani commented on src/shared/components/InputDate/InputDate.style.js
> +export const InputDate = styled.div`
o proprio InputDate pode ser do tipo input, não precisa ser uma div

2022-04-30 00:33 UTC, priscilaandreani commented on src/shared/components/InputDate/InputDate.jsx
> +        {...'dataNascimento'}
sem o register, essa destruturação não tem sentido algum

2022-04-30 00:33 UTC, priscilaandreani commented on src/shared/components/InputDate/InputDate.jsx
> +const InputDate = () => {
o register, como o "dataNascimento"

2022-04-30 00:53 UTC, priscilaandreani requested changes

2022-04-30 00:53 UTC, priscilaandreani commented on src/shared/components/InputDate/InputDate.style.js
> +export const InputDate = styled.div`
a nomenclatura do estilo não pode ser a mesma do componente

2022-04-30 00:57 UTC, priscilaandreani commented
Exemplo de componente reutilizavel:

```
export const InputDate = ({ defaultValue, registerValue  }) => {
  <input defaultValue={defaultValue} {...register(registerValue)} />;
};
```

e quando for utilizar no componente será: 

`<InputDate defaultValue="11/03/2020" register="dataNascimento" />`



**Atenção: essa não é a solução do seu problema, é um EXEMPLO.**

2022-05-04 12:14 UTC, priscilaandreani requested changes

2022-05-04 12:14 UTC, priscilaandreani commented on src/shared/components/InputDate/InputDate.jsx
> +        {...register(props.dataNascimento)}
É quase isso.. Só que o nome da propriedade deve ser genérica para ser utilizada em qualquer campo necessário. 

Usar desestruturação facilita muito.

2022-05-04 12:14 UTC, priscilaandreani commented on src/shared/components/InputDate/InputDate.jsx
> +        placeholder="dd/mm/aaaa"
o placeholder também deve ser uma prop

2022-05-04 12:14 UTC, priscilaandreani commented on src/shared/components/InputDate/InputDate.jsx
> +    <InputDateBirth>
Quando vc diz que esse input chama **InputDateBirth**, vc diz que ele só serve para uma coisa, data de nascimento. Mas esse não é o caso aqui, ele deve ser genérico.

2022-05-04 16:18 UTC, priscilaandreani commented
**Atenção aos commits que continuam sem serem semanticos e significativos!!** @leandrosax10

2022-05-06 16:22 UTC, leandrosax10 reviewed
@priscilaandreani

2022-05-06 17:14 UTC, priscilaandreani requested changes

2022-05-06 17:14 UTC, priscilaandreani commented on src/shared/components/InputDate/InputDate.style.js
> +  border-color: ${(props) => props.theme.colors.border_input};
essa cor `border_input` não existe no themes

2022-05-06 18:18 UTC, leandrosax10 commented on src/shared/components/InputDate/InputDate.style.js
> +  border-color: ${(props) => props.theme.colors.border_input};
Havia criado na outra branch, mas não subi. Acertei agora e vou subir a correção.

2022-05-06 18:22 UTC, leandrosax10 reviewed
@priscilaandreani

2022-05-08 23:46 UTC, priscilaandreani approved these changes

2022-05-09 12:13 UTC, merged